bcgov/mem-mmti-public

- src/app/app.component.html
- src/app/authorizations/authorizations.component.html
- src/app/authorizations/authorizations.component.scss
- src/app/compliance-oversight/compliance-oversight.component.html
- src/app/compliance-oversight/compliance-oversight.component.scss
- src/app/home/home.component.html
- src/app/lifecycle/lifecycle.component.html
- src/app/lifecycle/lifecycle.component.scss
- src/app/models/project.ts
- src/app/project/project.component.html
- src/app/project/project.component.scss
- src/app/project/project.component.ts
- src/app/services/project.service.ts
- src/assets/styles/components/accordion.scss
- src/assets/styles/components/aside.scss
- src/assets/styles/components/card.scss
- src/assets/styles/components/lists.scss
- Initial development of the Project List Page as well as adding routes / links for component
- Removed unnecessary styling from ASIDE component styling and leveraged the bootstrap card styling 
- Modified Compliance Oversight, Authorizations and Lifecycle pages to confirm to new styling (as above)
- Cleaned up LINT errors in projects.ts, project.component.ts
- Added accordion override style sheet
> EPIC-1135 - Projects List Page, Refactoring and Clean-up

- package.json
- src/app/app.component.html
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/topics-of-interest/topics-of-interest.component.html
- Added 'ng2-page-scroll' module to support jumping to named anchors with Angular 2
- Updated named anchor links in Topics of Interest page
- Leveraged new scroll module for the 'back to top' button
> EPIC-1135 - Adding scroll library to support jumping to named anchors

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/reclamation/reclamation.component.html
- src/app/reclamation/reclamation.component.scss
- src/app/reclamation/reclamation.component.spec.ts
- src/app/reclamation/reclamation.component.ts
- src/app/services/project.service.spec.ts
- src/app/services/project.service.ts
- src/app/tailings-management/tailings-management.component.html
- src/app/tailings-management/tailings-management.component.scss
- src/app/tailings-management/tailings-management.component.spec.ts
- src/app/tailings-management/tailings-management.component.ts
- src/app/topics-of-interest/topics-of-interest.component.html
- src/app/water-quality/water-quality.component.html
- src/app/water-quality/water-quality.component.scss
- src/app/water-quality/water-quality.component.spec.ts
- src/app/water-quality/water-quality.component.ts
- src/assets/styles/layout.scss
- Added Reclamation, Tailings Management and Water Quality topic components
- Cleaned up lint errors on project service typescript files
> EPIC-1135 - Adding Sub-topic page components

- src/app/app.component.html
- src/app/app.component.ts
- src/app/authorizations/authorizations.component.html
- src/app/contact/contact.component.html
- src/app/contact/contact.component.scss
- src/app/legislation/legislation.component.html
- src/app/news/news.component.ts
- Updating Contact Page Content
- Updating links to contact page
- Updating anchor links in the authorizations, legislation pages
- Fixed LINT issues in TS file.
> EPIC-1135 Adding Contact Page content

- src/app/app.component.html
- src/app/map/config/map-config.ts
- src/app/map/esri-map/esri-map.component.scss
- src/app/map/main-map/main-map.component.html
- src/app/map/main-map/main-map.component.scss
- src/app/map/main-map/main-map.component.ts
- src/app/projects/project-detail/authorizations/authorizations-tab-content.component.html
- src/app/search/search.component.html
- src/app/search/search.component.scss
- src/assets/styles/components/buttons.scss
- src/assets/styles/components/esri-map.scss
- src/assets/styles/header.scss
- src/assets/styles/themes/default.scss
- Updating map component markup / styling
- Added new main navigation item (Find Mines in BC)
- Switched/refactored scss to new naming conventions for search related views and components
> MEM-78 - UI updates & clean-up

- src/app/app.component.html
- src/app/search/search.component.html
- src/app/search/search.component.scss
- src/assets/styles/components/buttons.scss
- src/assets/styles/components/form-elements.scss
- src/assets/styles/components/hero-banner.scss
- src/assets/styles/header.scss
- src/assets/styles/helpers/mixins.scss
- src/assets/styles/themes/default.scss
MEM-478 - Website Cleanup
- Fixed wrapping issues with main navigation
- Fixed the loading spinner binding on the search page
- Fixed sizing issues with hero banner image
- Fixed spacing issues with search page banner
> MEM-478 - Website Cleanup

- src/app/search/search.component.html
- src/app/search/search.component.scss
- Styling updates for mobile 
- Fixed an issue where the toggle button would initiate the search functionality
> MEM-465 - Search UI Development

- src/app/models/collection.ts
- src/app/models/project.ts
- src/app/projects/project-detail/authorizations/authorizations-tab-content.component.html
- src/app/projects/project-detail/compliance/compliance-tab-content.component.html
- src/app/projects/project-detail/compliance/compliance-tab-content.component.scss
- src/app/projects/project-detail/compliance/compliance-tab-content.component.ts
- if no project operator, use ownership
- display the MEM Permit ID for EMPR permits in the Authorizations tab
- display Agency in the Compliance & Oversights tab
- hooked up sorting in the Compliance & Oversights tab
> MEM-522 Tweaks: Added MEM Permit ID, Inspection Agency

- src/app/filters/order-by.pipe.ts
- src/app/models/collection.ts
- src/app/projects/project-detail/authorizations/authorizations-tab-content.component.html
- src/app/projects/project-detail/compliance/compliance-tab-content.component.html
- src/app/projects/project-detail/compliance/compliance-tab-content.component.ts
- src/app/projects/projects.module.ts
- src/app/services/api.ts
- src/app/services/document.service.ts
- src/app/services/news.service.ts
- src/app/services/project.service.ts
- fixed collections/table sorting for dates
- added API class to facilitate better handling of API calls
> MEM-522 MMTI Hook-up tweaks. Fixed sorting. Improved API handling.

- src/app/app.component.html
- src/app/app.component.ts
- src/app/projects/project-detail/authorizations/authorizations-tab-content.component.scss
- src/app/projects/project-detail/compliance/compliance-tab-content.component.html
- src/app/projects/project-detail/compliance/compliance-tab-content.component.scss
- src/app/projects/project-detail/documents/documents-tab-content.component.scss
- src/app/projects/project-detail/project-detail.component.html
- src/app/projects/project-detail/project-detail.component.scss
- src/app/search/search.component.html
- src/app/search/search.component.scss
- src/app/topics-of-interest/topics-of-interest.component.html
- src/assets/styles/components/aside.scss
- src/assets/styles/components/buttons.scss
- src/assets/styles/components/feature-block.scss
- src/assets/styles/components/hero-banner.scss
- src/assets/styles/components/tab-nav.scss
- src/assets/styles/header.scss
- src/assets/styles/themes/default.scss
Stakeholder Revisions / General UI Clean-up
- Naming changes from 'Search' to 'Find Documents' (page and main navigation)
- Modified naming conventions in header and footer navigation
- Added window scroll behavior fix for IE11 (app.component.ts)
- Cleaned up the spacing on the compliance oversight tab component (table)
- Updated new naming conventions to the hero banner on the project detail page
- Fixed issues on content pages (removed redundant markup)
- Updated tab navigation component (UX research/feedback)
> MEM-465 - UI Clean-up / Updates

- src/app/projects/project-detail/authorizations/authorizations-tab-content.component.html
- src/app/projects/project-detail/compliance/compliance-tab-content.component.html
- src/app/projects/project-detail/documents/documents-tab-content.component.html
- src/app/search/search.component.html
Content changes in the authorizations tab intro
- Standardizing date display formats
- Fixed binding issues on the authorizations and compliance footer component.
> MEM-522 - Stakeholder Change Requests

- src/app/map/config/map-config.ts
- src/app/map/main-map/main-map.component.ts
MEM-496 ArcGIS - Mine Search (widget)
NOBUG: Use prod map for all environments
> MEM-514 ArcGIS - prevent user from zooming too far out

- src/app/search/search.component.html
- src/app/search/search.component.scss
- src/app/search/search.component.ts
- Added animation trigger for the loading indicator
> MEM-465 - Search UI Improvements / Fixes

- src/app/map/config/map-config.ts
- yarn.lock
* Update `yarn.lock` with bootstrap dependencies
> MEM-534 ArcGIS - disable map rotation

- src/app/map/main-map/main-map.component.ts
Remove filtering logic that shows only one mine on the map when navigating from the Project Page
> MEM-528 Show all mines on the map when navigating from Project Page

- src/app/authorizations/authorizations.component.html
- src/app/compliance-oversight/compliance-oversight.component.html
- src/app/contact/contact.component.html
- src/app/home/home.component.html
- src/app/legislation/legislation.component.html
- src/app/lifecycle/lifecycle.component.html
- src/app/news/news.component.html
- src/app/process/process.component.html
- src/app/projects/project-detail/project-detail.component.html
- src/app/projects/project-list/project-list.component.html
- src/app/reclamation/reclamation.component.html
- src/app/search/search.component.html
- src/app/search/search.component.scss
- src/app/tailings-management/tailings-management.component.html
- src/app/topics-of-interest/topics-of-interest.component.html
- src/app/water-quality/water-quality.component.html
- src/assets/js/utils.js
- Fixed an issue on some devices where the page title would collide with the main navigational components (header).
- Small positioning fix for search results
> MEM-539 - Fixed an issued with the header scroll behaviour

- src/app/app.component.html
- src/app/home/home.component.html
- src/app/projects/project-detail/compliance/compliance-tab-content.component.scss
- src/app/projects/project-detail/overview/overview-tab-content.component.html
- src/app/projects/project-detail/overview/overview-tab-content.component.scss
- src/app/search/search.component.html
- src/assets/js/utils.js
- src/assets/styles/components/hero-banner.scss
- src/assets/styles/header.scss
- src/assets/styles/themes/default.scss
- Removed 'home' navigation link in the header
- Removed unused markup from home page markup
- Hide the table header component in the compliance enforcement tab (evaluation of solutions in-progress)
- Minor styling fix for the project overview content / cleaned up markup
- Minor styling tweak regarding hero-banner heights for smaller devices
- Fixed an issue where the mobile navigation menu wouldn't collapse when navigating to a route
> MEM-539 - Minor Styling Tweaks / Usability Fixes

- src/app/app.component.ts
- src/app/search/search.component.ts
- src/app/services/api.ts
Initial plumbing for handling query params.
> MEM-540: Plumbing for unique URL handling.

- src/app/search/search.component.html
- src/app/search/search.component.scss
Small fix to address misleading result count for document search
> Fixed document results count

- LICENSE
- README.md
* Add Apache-2.0 license
* Fix typos, cleanup code examples in README file
> Create LICENSE, update README

- src/app/search/search.component.html
- Fixed an issued where the document anchors were not opening in a separate browser tab.
- Removed unused markup
> [MEM-579] Find Documents Bug Fix

- src/app/home/home.component.html
Updating the Environmental Assessment Count to '5'.
> Updating EA Application count

- src/app/projects/project-detail/project-detail.component.ts
Minor: fixed code indentation.
> EM-82: indentation fix

- src/index.html
Turned on IP anonymization for Google Analytics.
- In index.html <head>, added 'anonymize_ip' parameter to gtag <script> & set it to true.
> Added IP anonymization parameter to Google Analytics tracking script

- src/index.html
Removed extra spaces in GA parameter script.
> Fixed spacing in Google Analytics tracking script

- src/app/projects/project-list/project-list.component.html
- src/app/projects/project-list/project-list.component.scss
- Added a mine's project status as a column to the project list table
- Styled table so the columns are the appropriate size for their data type.
> Added mine status to project list table

- src/app/app.module.ts
- src/app/operator-filter.pipe.spec.ts
- src/app/operator-filter.pipe.ts
- src/app/project-status-filter.pipe.spec.ts
- src/app/project-status-filter.pipe.ts
- src/app/project-type-filter.pipe.spec.ts
- src/app/project-type-filter.pipe.ts
- src/app/projects/project-list/project-list.component.html
- src/app/projects/project-list/project-list.component.ts
- src/app/projects/projects.module.ts
- src/app/shared/shared.module.ts
- src/assets/styles/components/filter-bar.scss
- src/assets/styles/themes/default.scss
Added filter bar and filters to the projects page.
Able to filter by:
- Project Name
- Operator
- Type
- Status
> em-184 added filter bar and filters to projects page

- sonar-runner/build.gradle
> Updated SonarQube configuration to use better build names.

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/not-found/not-found.component.html
- src/app/not-found/not-found.component.spec.ts
- src/app/not-found/not-found.component.ts
> 404 Pages Provide no information to users
- Added a basic 404 component with a home button redirect
> EM-34: basic 404 page added to Mines

- src/app/services/project.service.ts
Default date sorts descending even if the page is refreshed or hit directly.
> em-222 default date sort shows descending even after page refresh

- src/app/search/search.component.html
- src/app/search/search.component.ts
> Date picker in "Find Documents" on mines.nrs doesn't let you pick a date before 2008
- Changed date picker to accept dates between 1/1/1900, and present day
- Also modified date picker so that start date must always select a date before the selected end date
> EM-291 fix and date picker optimization

- src/app/app.component.html
- src/assets/styles/footer.scss
> Hover style on Submit Feedback button on MMTI makes text illegible
- SCSS change to keep text white on hover.
- Added new class for Submit button, so that other links would be unaffected by this change.
> EM-289 fix for MEM

- Jenkinsfile
Updated configuration in Jenkinsfile for newer openshift3/jenkins-2-rhel7
I literally copied over the newer pipeline configuration from eao-public and tweaked it for mem-mmti-public.
@RandyInVictoria : this re-enables pipeline builds for mem-mmti, but we may need additional work if we need  pipeline jobs also for the geoservice, nginx, etc.
> Updated configuration in Jenkinsfile

- src/app/models/project.ts
- src/app/projects/project-detail/project-detail.component.html
This pull request needs to be processed together with the pull request for the same issue on **mem-admin**, as the new fields are exposed via changes to the API.
@RandyInVictoria
> EM-185: Added employment to project details page.

- src/app/authorizations/authorizations.component.html
- src/app/contact/contact.component.html
Changed the two instances of "Ministy" to "Ministry"
> em-462 fixed spelling mistakes

- src/app/search/search.component.html
- src/app/search/search.component.scss
- Commented out the blocks of code for the advanced filters.
- Moved the date range filter to below the keywords filter
- Added temp styling to adjust margins of buttons
> em-452 hide advanced filter fields

- src/app/services/project.service.ts
* Patch Observable.forkJoin() so it works with empty arrays
> Hotfix for EM-485 MMTI Project Page doesn't work (PRODUCTION)

- .gitignore
- src/app/projects/project-list/project-list.component.html
- src/app/projects/project-list/project-list.component.scss
- Changed scss and html to add responsive styling for projects table
- Removed lines allowing git commits of localized .vscode settings files from .gitignore file after confirming with @esune
> em-287 Added responsive styling to projects table on projects list page

- src/app/compliance-oversight/compliance-oversight.component.html
Fixed broken link in mmti-public on the compliance and oversight page
> em-450 changed link to new link

- src/app/contact/contact.component.html
- src/app/services/api.spec.ts
> Contact form submit button does not work in mines.nrs
- Added email functionality for user feedback
- Added .spec file for api (technical debt)
> EM-128 fix for MEM public

- src/app/models/collection.ts
Updated the view for the public site to display more than one main document.
> EM-42: Add support for multiple "main" documents in collections.

- src/app/home/home.component.html
- src/app/home/home.component.ts
Removed html reference to private api. Created public variable to hold path to admin website
> EM-322-hotfix

- src/app/models/collection.ts
Filtered documents to only include published files.
> EM-760: Unpublished documents showing in MEM public

- .gitignore
- karma.conf.js
- package.json
- src/app/authorizations/authorizations.component.spec.ts
- src/app/filters/order-by.pipe.spec.ts
- src/app/filters/order-by.pipe.ts
- src/app/home/home.component.spec.ts
- src/app/map/config/map-config.service.spec.ts
- src/app/map/main-map/main-map.component.spec.ts
- src/app/map/widgets/widget-builder.spec.ts
- src/app/object-filter.pipe.spec.ts
- src/app/operator-filter.pipe.spec.ts
- src/app/project-status-filter.pipe.spec.ts
- src/app/project-type-filter.pipe.spec.ts
- src/app/projects/project-detail/authorizations/authorizations-tab-content.component.spec.ts
- src/app/projects/project-detail/compliance/compliance-tab-content.component.spec.ts
- src/app/projects/project-detail/documents/documents-tab-content.component.spec.ts
- src/app/projects/project-detail/project-detail.component.spec.ts
- src/app/projects/project-list/project-list.component.spec.ts
- src/app/projects/project-list/project-list.component.ts
- src/app/services/api.spec.ts
- src/app/services/api.ts
- src/app/services/project.service.spec.ts
- src/app/services/project.service.ts
- src/app/services/proponent.service.spec.ts
- yarn.lock
- Refactor code to expose certain parts for easier testing
- Have 60% branch coverage
> em-801 have 60% branch coverage for unit tests

- src/app/authorizations/authorizations.component.html
- src/app/lifecycle/lifecycle.component.html
- Removed broken links or replaced them with working ones as per P.O.'s specifications
> EM-665: Fix/remove broken links on MMTI Public

- src/app/models/collection.ts
EM-893: Fix for projects not displaying due to references to old/non-existing documents.
> EM-893: Fix for projects not displaying due to references to old/non-existing documents.

- src/app/projects/project-detail/project-detail.component.spec.ts
- src/app/search/search.component.html
- src/app/search/search.component.scss
- src/app/search/search.component.spec.ts
- src/app/search/search.component.ts
- src/assets/styles/components/form-elements.scss
Add Clear Filter buttons to Find Documents page.
> EM-887: Add Clear Filter buttons to Find Documents page.

- src/app/search/search.component.html
- src/app/search/search.component.scss
Additional Fixes
- Cleaned up the footer page count styling
- Updated the count messaging
> [EM-958] Fix Search Descriptive text wrapping issue in IE

- .editorconfig
- src/app/map/config/map-config.service.ts
- src/app/map/main-map/main-map.component.html
- src/app/map/main-map/main-map.component.scss
- src/app/map/main-map/main-map.component.ts
- src/app/map/project-map/project-map.component.ts
- src/app/map/support/map-utils.ts
- refactor code into a separate `map-utils` helper
- allow searching the mines point layer by title
EM-1021: Add button to show/hide all mine boundaries
- add button, supporting logic to map component
> EM-83: Display shapefiles on map

- src/app/map/main-map/main-map.component.html
- src/app/map/main-map/main-map.component.ts
- auto-open the map disclaimer modal on page load
- use generic disclaimer (loren ipsum), to be replaced later
- show map disclaimer only once. Do not show on subsequent visits
> EM: ArcGIS - Add general disclaimer text to web site

- src/app/map/support/map-utils.ts
- get topmost graphic from the Major Mines layer, while ignoring other layers (e.g. shapefiles)
Fixes EM-1132
> EM-1132: Map hover tooltip shows "undefined" for mine boundaries

- src/app/compliance-oversight/compliance-oversight.component.html
- src/app/enforcement-actions/enforcement-actions.component.html
waiting on approval for old change so we removed it temporarily to be able to push new change to prod.
> reverted older change to hide from prod

- src/app/compliance-oversight/compliance-oversight.component.html
- src/app/enforcement-actions/enforcement-actions.component.html
add back the changes removed in the last commit.
> recommit old changes

- src/app/map/leaflet-map/leaflet-map.component.ts
Update project details to use leaflet map, open map view on click, show pin when available (done in a previous PR), and turn on major mines WMS layer (last missing part, done here).
See ticket [NRPT-211](https://bcmines.atlassian.net/browse/NRPT-211)
> NRPT-211: Project details mini-map

- src/app/map/main-map/main-map.component.html
- src/app/map/main-map/main-map.component.scss
- src/app/map/main-map/main-map.component.ts
See Ticket [NRPT-173](https://bcmines.atlassian.net/browse/NRPT-173)
> NRPT-173: Adding disclaimer modal and button

- src/app/map/leaflet-map/leaflet-map.component.ts
See Ticket [NRPT-183](https://bcmines.atlassian.net/browse/NRPT-183)
> NRPT-183-2: Renaming Verified Mines layer to Major Mines Permitted Areas

- src/app/map/leaflet-map/leaflet-map.component.ts
- src/app/map/leaflet-map/leaflet-map.utils.ts
- src/app/map/leaflet-map/major-mines-popup/major-mines-popup.component.html
- src/app/map/leaflet-map/major-mines-popup/major-mines-popup.component.scss
- src/app/map/leaflet-map/major-mines-popup/major-mines-popup.component.ts
- src/app/map/leaflet-map/project-popup/project-popup.component.html
- src/app/map/leaflet-map/project-popup/project-popup.component.scss
- src/app/map/main-map/main-map.component.spec.ts
- src/app/map/map.module.ts
Adding a detailed popup for the verified mines WMS layer.
See Ticket [NRPT-205](https://bcmines.atlassian.net/browse/NRPT-205)
> NRPT-205: Adding popup for Verified Mines layer

- src/app/projects/project-list/project-list.component.html
- src/app/projects/project-list/project-list.component.spec.ts
- src/app/projects/project-list/project-list.component.ts
Removing the Mine Status filter on the Mines list page as per comments. Remainder of ticket addressed in previous PR.
See comments in ticket [NRPT-158](https://bcmines.atlassian.net/browse/NRPT-158)
> NRPT-158: Remove Mine Status filter

- src/app/services/api.ts
Small fix to replace the original sort of `dateIssues` with `name`.
See ticket [NRPT-255](https://bcmines.atlassian.net/browse/NRPT-255)
> NRPT-255: Set order on getProjects to alphabetical

- src/app/map/leaflet-map/geocode-popup/geocode-popup.component.html
- src/app/map/leaflet-map/geocode-popup/geocode-popup.component.scss
- src/app/map/leaflet-map/geocode-popup/geocode-popup.component.ts
- src/app/map/leaflet-map/leaflet-map.component.ts
- src/app/map/main-map/main-map.component.html
- src/app/map/main-map/main-map.component.spec.ts
- src/app/map/main-map/main-map.component.ts
- src/app/map/map.module.ts
- src/app/map/search/search.component.html
- src/app/map/search/search.component.scss
- src/app/map/search/search.component.spec.ts
- src/app/map/search/search.component.ts
- src/app/services/api.ts
- src/app/services/geocoder-api.ts
- src/app/services/geocoder.service.ts
- src/app/shared/constants.ts
- src/assets/images/marker-icon-blue.svg
* [NRPT-177](https://bcmines.atlassian.net/browse/NRPT-177) add geocoder to map search
> add address lookup with BC Geocoder to map search

- src/app/projects/project-detail/overview/overview-tab-content.component.scss
- src/app/projects/project-detail/project-detail.component.html
- src/app/projects/project-detail/project-detail.component.scss
- src/assets/styles/components/leaflet-map.scss
Ticket: https://bcmines.atlassian.net/browse/NRPT-256
Maintains any whitespace that was entered in the textbox on the admin side.
> NRPT-256: Maintains whitespace for description and summary

- src/index.html
See ticket [NRPT-329](https://bcmines.atlassian.net/browse/NRPT-329)
> NRPT-329: Snowplow updates

- src/app/projects/project-detail/documents/documents-tab-content.component.html
- src/app/projects/project-detail/documents/documents-tab-content.component.spec.ts
- src/app/projects/project-detail/documents/documents-tab-content.component.ts
See ticket [NRPT-307](https://bcmines.atlassian.net/browse/NRPT-307)
> NRPT-307: Added agency and sort to other docs tab

- functional-tests/src/test/groovy/modules/FooterModule.groovy
- functional-tests/src/test/groovy/specs/HomeSpec.groovy
- src/app/app.component.html
- src/app/map/leaflet-map/major-mines-popup/major-mines-popup.component.html
- src/app/map/leaflet-map/project-popup/project-popup.component.html
Ticket: https://bcmines.atlassian.net/browse/NRPT-314
Updates the site to refer to everything as a "mine."
> NRPT-314: Updates Project Verbiage

- src/app/projects/project-detail/documents/documents-tab-content.component.scss
Small update to header spacing regarding comments from NRPT-307
See ticket [NRPT-307](https://bcmines.atlassian.net/browse/NRPT-307)
> NRPT-307: Update header css
